name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # ejecuta cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Colores temáticos de videojuegos (verde oscuro y verde claro)
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: "#00FF00"
          grid_color: "#003300"

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: 'Actualización de la animación del gráfico de contribuciones'
          add: "dist/github-contribution-grid-snake-dark.svg"